# Generated by Django 5.2.5 on 2026-01-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
